package de.BenediktKurth.view;

import de.BenediktKurth.control.MainWindowController;

/**
 *
 * @author clannick
 */
public class Umbennen extends javax.swing.JFrame {

    
    private final MainWindowController controller;
    private final int interneID;
    /**
     * Creates new form Umbennen
     */
    public Umbennen(int interneID, String label, MainWindowController controller,int screenHeight, int screenWidth) {
        this.controller = controller;
        this.interneID = interneID;
        initComponents();
        super.setBounds((screenWidth/2)-60, (screenHeight/2)-125, 250, 120);
        super.setResizable(false);
        super.setSize(200, 120);
        super.setLayout(null);
        textFeld.setText(label);
        super.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFeld = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Umbenennen");
        setMaximumSize(new java.awt.Dimension(250, 120));
        setMinimumSize(new java.awt.Dimension(250, 120));
        setPreferredSize(new java.awt.Dimension(250, 120));
        setSize(new java.awt.Dimension(250, 120));
        getContentPane().setLayout(new java.awt.FlowLayout());

        textFeld.setText("jTextField1");
        textFeld.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(textFeld);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setText("Abbrechen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String temp = textFeld.getText();
        controller.umbennenLabel(interneID, temp);
        controller.neueDarstellungOhneTest();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField textFeld;
    // End of variables declaration//GEN-END:variables
}
